### ISSUE TITLE
Unable to run chapter 6 on Python 3.10 installed

### ISSUE THREAD

**Issue by sevapopov2** [AutomationPanda/tau-pytest-bdd#10]
When running rest API tests from chapter 6 there is an error that all tests are failed due to the second argument "example_converters" can't be found in scenarios function.
The same problem appears when completing this chapter by myself on my own training repo.
Error output log is attached.
Reproduced on:
Arch Linux
Python 3.10
pytest 7.1.2
pytest-bdd 6.0.1.
VSCode Insiders version 1.65.
[error_output.log](https://github.com/AndyLPK247/tau-pytest-bdd/files/9232300/error_output.log)

**Comment by AutomationPanda** [comment]
Sorry for delaying to reply so long. I'm aware of the issues, and I hope to make some updates soon.
